### ISSUE TITLE
Bug: Minor Search bug

### ISSUE THREAD

**Issue by drago87** [SkinnyDevi/webui_tavernai_charas#8] opened 2024-01-14 19:28 UTC
**Describe the bug**
Does not switch to page 1 when changing Category in search mode witch can give you seemingly empty Categories

**Steps To Reproduce**
1. Go to 'Search'
2. Click on 'a page number larger then 1'
3. Change 'Category to one with less then the page number you clicked'

**Additional context**
The second category needs to have less pages then the page number you are on

**Comment by SkinnyDevi** [comment] 2024-01-29 19:52
Hi there! Sorry for the late response.

I was trying to reproduce your issue and found the following results:
- No error was displayed while testing
- If by error you mean empty pages, everything is working fine. This just means the were no cards matching your search criteria.

The following steps were taken:
1. Go to 'Search' (NSFW **not** allowed)
2. Clicked on 'Next Section' (page number is now 2)
3. Clicked on category '2girls'
4. Pages are empty due to no cards matching search criteria
5. Clear search filters

1. Go to 'Search' (NSFW **is** allowed)
2. Clicked on 'Next Section' (page number is now 2)
3. Clicked on category '2girls'
4. Pages is populated with 1 card as per the according search filter criteria
5. Clear search filters

If you could provide a more detailed way to reproduce your issue, i'd be glad to help out.

Suggestion: Have you updated you text-generation-webui to the latest release?

If your issue has been resolved, please close the issue. Thank you!

**Comment by drago87** [comment] 2024-01-29 20:03
If you go to Search enable "NSFW" and go to "Furry" you will see `Pages:1 2 3 4 5` change page to page 5 then you change to "fogirlx"
The page is now empty but you can see `Pages:1` and you can press on the 1 and see the result "witch is 3 cards while writing this".
A fix would be to always set the page to 1 when changing `Categories`

**Comment by SkinnyDevi** [comment] 2024-01-29 20:07
Alright, I see the problem now. I'll find a way to fix it. Thank you!

**Closed** 2024-01-29 21:54 UTC
Labels: bug, applied next update
